### ISSUE TITLE
MVP Field Types

### ISSUE THREAD

**Issue by pablocubico** [coralproject/elkhorn#11]
Namely:
- [x] short text
- [x] longer text
- [ ] location
- [x] numbers
- [x] multiple choice
- [x] email address
- [ ] date

A note on **multiple choice**: if `allow multiple` is checked, it will render checkboxes, otherwise it would render radio buttons.

A check on the list means that we have figured out:
- General Spec
- Data structure
- Validation
- Keyboard nav
- Config form

**Comment by impronunciable** [comment]
@pablocubico How about making numbers and emails just validations for text?

**Comment by pablocubico** [comment]
@impronunciable Sure, currently, email is a field text with email type validation on the elkhorn side.

**Comment by pablocubico** [comment]
@losowsky :
- What is "numbers"?
- What's the difference between a dropdown and a multiple choice field? By "dropdown" you mean an autocomplete field with suggestions?

**Comment by pablocubico** [comment]
@losowsky  I just remembered a simple dropdown case: countries. Nevermind.

**Comment by losowsky** [comment]
"Numbers" - numbers only data field
Dropdown: http://semantic-ui.com/modules/dropdown.html
Multiple Choice = checkbox where you can select multiple options: http://semantic-ui.com/modules/checkbox.html

**Comment by pablocubico** [comment]
There is another issue referencing field types: #9

**Comment by kgardnr** [comment]
Remove location, break this down into individual tasks
