### ISSUE TITLE
Elkhorn is not generating S3 URLs correctly

### ISSUE THREAD

**Issue by jtnelson** [coralproject/elkhorn#124]
Elkhorn should use the region to generate the S3 url instead of relying on a baseUrl config value.

For example, this is the kind of URL that elkhorn generates:
![image](https://cloud.githubusercontent.com/assets/1495450/19761788/389686b0-9c2f-11e6-8938-37ac17bc6f10.png)

If you try to go to that page (https://s3.amazonaws.com/ask-stg/5811be4bc155900001a0e3c1.html) you get an error.

The correct URL is https://s3-us-west-2.amazonaws.com/ask-stg/5811be4bc155900001a0e3c1.html, according to the docs at http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

**Comment by jde** [comment]
This is an interesting difference. All current installs that use s3 generate urls that looks like this: `https://s3.amazonaws.com/ask-stg/580627b42600e2035218509f.html`

Seeing the error on forms that have been working.  Fixing now.

**Comment by jde** [comment]
@wyattjoh had the best suggestion here. As we cannot depend on any pattern from aws, we should require that users enter the base url explicitly using the existing `published_base_url` flag.

This will be accessible to them when they create the bucket.  Adding to the ask-install docs now.
