### ISSUE TITLE
Persist intermediate states (autosave) [user form]

### ISSUE THREAD

**Issue by pablocubico** [coralproject/elkhorn#2]
We need an autosave approach to persist the form state in case a user accidentaly closes the browser window, loses connection, etc.

**Comment by impronunciable** [comment]
@pablocubico POST creates, PUT updates

**Comment by impronunciable** [comment]
We need to create the endpoint thou

also need to integrate with the auth system for permissions on update.

**Comment by pablocubico** [comment]
Ahhh, persisting to an endpoint, we might need that. I was just thinking on persisting locally.

**Comment by pablocubico** [comment]
Just to be clear: I'm speaking of end-user asks (embeddable forms), not the form builder in Cay.

**Comment by impronunciable** [comment]
Oh, I see. My fault.
