### ISSUE TITLE
Reader can view an embedded gallery on an article or as a separate page

### ISSUE THREAD

**Issue by jde** [coralproject/elkhorn#45]

**Comment by egrdina** [comment]
Reader-facing vertical gallery names on bottom
![screen shot 2016-07-06 at 3 55 39 pm](https://cloud.githubusercontent.com/assets/7856099/16632458/2f79b2e6-4392-11e6-96b5-5202decca557.png)

Reader-facing vertical gallery names on top
![screen shot 2016-07-06 at 3 55 45 pm](https://cloud.githubusercontent.com/assets/7856099/16632459/2f7a77da-4392-11e6-8b2a-b91e65ae4e43.png)

Reader-facing horizontal gallery names on bottom
![screen shot 2016-07-06 at 3 55 50 pm](https://cloud.githubusercontent.com/assets/7856099/16632461/2f7ed6cc-4392-11e6-8fab-0f3ddef7af77.png)

Reader-facing horizontal gallery names on top
![screen shot 2016-07-06 at 3 55 54 pm](https://cloud.githubusercontent.com/assets/7856099/16632460/2f7e040e-4392-11e6-9a0e-3efa604cdfa3.png)

**Comment by kgardnr** [comment]
We need to add submission #s as per:
![screen_shot_2016-07-07_at_4 19 21_pm 1](https://cloud.githubusercontent.com/assets/1077300/16779518/3ed14c0e-4838-11e6-9f0c-57525362070c.png)
![screen_shot_2016-07-07_at_4 19 21_pm](https://cloud.githubusercontent.com/assets/1077300/16779521/3fec92b0-4838-11e6-81c1-86eb3285621d.png)
![screen_shot_2016-07-07_at_4 19 27_pm](https://cloud.githubusercontent.com/assets/1077300/16779523/42266704-4838-11e6-9475-f5c371cb8467.png)
