### ISSUE TITLE
Elkhorn api gives 502 error on create

### ISSUE THREAD

**Issue by kgardnr** [coralproject/elkhorn#47]
https://demo.coralproject.net/elkhorn_api/create 

`Failed to load resource: the server responded with a status of 502 ()`

Steps to reproduce:
1. Try to save new Ask
2. No error on frontend
3. Console gives above error

**Comment by impronunciable** [comment]
502 means the app is down. @edefikh is elkhorn up?

**Comment by edefikh-zz** [comment]
I adjusted demo to use our stage elkhorn https://elkhorn.coralproject.net, please test on demo web UI.
