### ISSUE TITLE
Gallery manager and gallery preview show different content for PII

### ISSUE THREAD

**Issue by jde** [coralproject/elkhorn#73]
Note here:
http://ec2-54-175-45-178.compute-1.amazonaws.com/forms/5798fdd1c0bbf70007328934/gallery

The the gallery manager shows three names:
_Anon..., undecided_
_Anon..._
_J. J._

On the gallery preview:
Blank
_Samir..._
_J. J._

<img width="691" alt="screen shot 2016-07-28 at 8 22 16 am" src="https://cloud.githubusercontent.com/assets/259957/17218415/8349afe6-549c-11e6-8b46-47f6e2d2ffa7.png">

**Comment by impronunciable** [comment]
@jde cannot reproduce this in master and also think this was fixed recently. Is the ec2 instance paired with master? can you try again?
