### ISSUE TITLE
Request text submissions from readers

### ISSUE THREAD

**Issue by egrdina** [coralproject/elkhorn#9]
Journalists should be able to select (most likely in a drag and drop interaction style) from a list in order to create their form. 

Text fields the list should include are as follows: 
- Name
- Email 
- DOB 
- Phone number 
- City 
- State 
- Country 
- Select multiple answers (this might manifest as radio buttons and/or a dropdown) 
- Select one answer from a list (for use on a question like "What is your income level?"
- Text without a character limit
- Text with a character limit

**Comment by theysamtheirs** [comment]
I think we are looking for the multiple choice: radio, drop down, and probably checkboxes (since the first two are designated usually for single selection).

**Comment by impronunciable** [comment]
BTW you can see what we already did at http://pablocubi.co/ask/ just to get more ideas :)

**Comment by theysamtheirs** [comment]
In the next couple days I will be doing an audit of the form fields to make sure we have accounted for the correct "settings" within each field type. Should I create them as separate issues? Or would you like me to add those here? I realize we have this issue as well as #11 (and maybe elsewhere in cay -- but i'm not sure). @egrdina will also be following up with visual designs for each type.
