### ISSUE TITLE
Adding Access-Control-Allow-Origin: * to xhr form requests

### ISSUE THREAD

**Issue by jde** [coralproject/elkhorn#92]
Form submissions are throwing cors errors due to lack of allow origin headers:

![screenshot 2016-09-09 12 20 58](https://cloud.githubusercontent.com/assets/259957/18394425/f780a9e8-7687-11e6-8901-c446f78f708a.png)

**Comment by jde** [comment]
After adding the Allow-Access header, it's reporting that this header is not allowed in OPTIONS:

![screenshot 2016-09-09 13 57 04](https://cloud.githubusercontent.com/assets/259957/18397460/514c8b46-7696-11e6-8ce2-4ae772d14b47.png)

The cors strategy on elkhorn published files should be the same as requests coming from Cay.

**Comment by impronunciable** [comment]
@jde I think the issue is that pillar is not sending the header.

**Comment by impronunciable** [comment]
The preflight request is triggered by the browser and the server should respond to it with the headers

https://stackoverflow.com/questions/32500073/request-header-field-access-control-allow-headers-is-not-allowed-by-itself-in-pr

**Comment by jde** [comment]
You are correct.  The server does need to reply with that header on OPTIONS.

The odd thing here is that the headers for this endpoint are set by the exact same code that handles every other api request:

https://github.com/coralproject/shelf/blob/master/vendor/github.com/ardanlabs/kit/web/app/app.go#L134

This code allows all the requests from Cay to work.  Is there a difference in the way the requests are being made?

**Comment by impronunciable** [comment]
@jde preflight requests are sent for post/put/delete but I understand we are using post in cay right? it's weird indeed.

**Comment by jde** [comment]
Actually, the server is returning the headers as expected.  

![screenshot 2016-09-09 14 48 31](https://cloud.githubusercontent.com/assets/259957/18398861/8e7a93f4-769c-11e6-8588-69bbc95cbc8f.png)

Note that the OPTIONS response does contain the expected headers, including the allow-origin: *.

**Comment by jde** [comment]
This is resolved. It seems to have come from networking issues.
